### PR TITLE
refactor(server/updater): fix updater always results outdated issue

### PR DESCRIPTION
**Pull request by wobozkyng**

### CODE REVIEW

**Comment by ImXirvin** [comment]
Whoops, thanks for noticing and fixing it

**Review by ImXirvin — APPROVED** [review]

**Comment by ImXirvin** [comment]
Actually Im gonna have to revert it, I didnt realise that the manifest was changed due to a formatting option I had on my VSCode.

**Comment by wobozkyng** [comment]
Do you mean the parentheses thing? I thought that was intentional.

**Comment by ImXirvin** [comment]
Yeah it wasnt, just didnt notice the formatter did that

**Pull request merged**
